services:
  postgres:
    image: postgres:17.6
    container_name: apicorretor-postgres
    restart: always

    environment:
      POSTGRES_DB: corretor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    networks:
      - dev-network

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  dev-network:
    external: true