package com.nerdev.auxcorretor.model.enums;

public enum PlanoEnum {

    CORRETOR_INDIVIDUAL_BASIC,
    CORRETOR_INDIVIDUAL_PLUS,
    CORRETOR_INDIVIDUAL_PREMIUM,
    IMOBILIARIA_BASIC,
    IMOBILIARIA_PLUS,
    IMOBILIARIA_PREMIUM;

}
